security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        application_provider:
            entity:
                class: App\Entity\User
        api_provider:
            entity:
                class: App\Entity\Application

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            anonymous: false
            provider: api_provider

            guard:
                authenticators:
                    - App\Security\Api\TokenAuthenticator

        main:
            pattern: ^/
            anonymous: true
            provider: application_provider

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path:     /(admin|en/admin)

            logout:
                path: logout
                target: login


    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/login , roles: IS_AUTHENTICATED_ANONYMOUSLY}
         - { path: ^/api, roles: ROLE_API_APPLICATION }
