parameters:
    system_email: '%env(SYSTEM_EMAIL)%'
    twilio_sid: '%env(TWILIO_SID)%'
    twilio_token: '%env(TWILIO_TOKEN)%'
    twilio_number: '%env(TWILIO_NUMBER)%'

services:

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventSubscriber\NotificationSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\Service\EmailService:
        arguments:
            - '%system_email%'

    twilio.client:
        class: Twilio\Rest\Client
        arguments:
            - '%twilio_sid%'
            - '%twilio_token%'

    App\Service\SmsService:
        arguments:
            - '%twilio_number%'
            - '@twilio.client'
